import Head from "next/head";
import { useRouter } from "next/router";
import { CardsList } from "@/components/CardsList/CardsList";
import { PageSizeBtns } from "@/components/PageSizeBtns/PageSizeBtns";
import { Pagination } from "@/components/Pagination/Pagination";
import { SearchBar } from "@/components/SearchBar/SearchBar";
import { wrapper } from "@/store/store";
import {
  getData,
  getRunningQueriesThunk,
  useGetDataQuery,
} from "@/store/dataApi";
import "./index.css";

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    const searchValue = context.query.searchValue || "news";
    const pageSize = context.query.pageSize || "10";
    const page = context.query.page || "1";

    if (typeof searchValue === "string") {
      store.dispatch(
        getData.initiate({
          searchValue,
          pageSize,
          page,
        })
      );
    }

    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return {
      props: {},
    };
  }
);

export default function Home() {
  const router = useRouter();

  const searchValue = router.query.search || "news";
  const pageSize = router.query.limit || "10";
  const page = router.query.page || "1";

  const { data } = useGetDataQuery({
    searchValue: searchValue,
    pageSize: pageSize,
    page: page,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="search-controls">
          <SearchBar />
          <PageSizeBtns />
          <Pagination />
        </div>

        <CardsList cards={data?.articles} />
      </>
    </>
  );
}
